### PR TITLE
Update project to Godot 4 beta 17 (animations still not fully updated)

### PR DESCRIPTION
**Pull request by Brawmario**
Godot commit that made this change necessary: https://github.com/godotengine/godot/commit/bf1571979cd3cd90b2b5c4581b2947450aa4cd9d

### CODE REVIEW

**Comment by Brawmario** [comment]
I'll attempt to also fix these issues, I'll update this pull request with the new changes, thanks for pointing it out!

**Comment by Brawmario** [comment]
I gave a shot at updating the project however I'm inexperienced with 3D animations and AnimationTrees. I fixed the shaders and the one call to the OneShot parameter to make the project work without any hard errors but some animations are still broken, like the player running cycle.

**Comment by geowarin** [comment]
I think all calls to `travel()` need to be wrapped in `if state_machine.get_current_node() != "anim":` like this:

```gdscript
func set_moving(value : bool):
	moving = value
	if moving:
		if state_machine.get_current_node() != "move":
			state_machine.travel("move")
	else:
		if state_machine.get_current_node() != "idle":
			state_machine.travel("idle")
```

I might be wrong though. Here [is the PR](https://github.com/godotengine/godot/pull/71418) that changed the AnimationTree.

**Comment by Brawmario** [comment]
Thanks @geowarin! That seems to be the case, I'll update this PR with the fix

**Comment by Brawmario** [comment]
The only thing seemingly left is the Beetles T posing, only the death animation is functioning correctly and it doesn't seem to stem from the travel reseting the animation in anyway

**Comment by NathanLovato** [comment]
Thank you very much for taking the time to help! Would you like a hand in figuring out the cause of this T-posing issue?

**Comment by Brawmario** [comment]
> Thank you very much for taking the time to help! Would you like a hand in figuring out the cause of this T-posing issue?

Yes I would! I can't see why the animations for the beetle is broken when all the others aren't, I feel like this is the only outstanding issue right now stopping the project from fully being updated and functioning.

Also when opening the project in beta 16 it generates a bunch of PNG files extracted from the GLB files. I'll avoid committing them for now but I don't know how they should be dealt with.

**Comment by geowarin** [comment]
It might be this setting in the gltf files:

image

It [changed recently](https://github.com/godotengine/godot/pull/62499)

**Comment by Brawmario** [comment]
I see. So apparently extracting the files is the way forward. I don't feel comfortable just committing the generated PNGs so I'll just ignore it for now, it doesn't seem to have anything with the broken Beetle animations.

**Comment by akien-mga** [comment]
For the record, after https://github.com/godotengine/godot/pull/72450 is merged, the animation travel changes may no longer be needed.

**Comment by Brawmario** [comment]
Thanks for the heads up @akien-mga , I'll check and undo the travel changes when a next beta gets released with this update.

**Comment by geowarin** [comment]
> I see. So apparently extracting the files is the way forward. I don't feel comfortable just committing the generated PNGs so I'll just ignore it for now, it doesn't seem to have anything with the broken Beetle animations.

Maybe not :smile: !

"Embed as uncompressed" will be an option again very soon:
https://github.com/godotengine/godot/pull/72440

**Comment by akien-mga** [comment]
Yeah sorry for the back and forth on the API. As we get really close to RC and *really* freezing the API the maintainers find things which are absolutely needed to finalize and there's a bit of experimentation on the API side :)

**Comment by lyuma** [comment]
@geowarin I advise against using embed as uncompressed for a demo project as it teaches people a bad workflow that will lead to huge wastings of 400% to 800% VRAM usage. (Unless this is a pixel art game)

If you need embedding, use Embed as Basis, or else consider adjusting your workflow so you can use gltf separate files with textures already extracted.

there's a reason Embed as Uncompressed was originally removed.

**Comment by geowarin** [comment]
Thanks for chiming in @lyuma. Having separate textures is usually a better choice, I think.

But this is a tradeoff (workflow is a bit more complex) that the guys at GDQuest will have to figure out. I think Godot maintainers did a great job with the naming to make this choice more obvious.

I'd hate to hijack this PR but can I get you all to look at [this proposal](https://github.com/godotengine/godot-proposals/issues/6198) of mine? I noticed that all the models in this project are facing backwards (towards +Z) and this was really confusing for me.

**Comment by Brawmario** [comment]
Thanks for the insight @lyuma. However this PR is just primarily concerned in making the demo work again on the more recent Godot beta releases. I'll use the Embed as Uncompressed for now as it's the least intrusive option. Maybe after this PR is merged an issue could be opened to track this matter.

**Comment by NathanLovato** [comment]
@lyuma what would you recommend regarding models? Reimporting them with textures and other files sitting next to the glb file? Or are we talking about something else?

**Comment by NathanLovato** [comment]
@Brawmario is this PR ready to review and merge? If so we'll review and merge this week.

**Comment by Brawmario** [comment]
By me I'd say it's ready. I couldn't tackle fixing the beetles animation due to my lack of knowledge on 3d animation however the project now does run successfully on Beta 17 with all other API changes accounted for (as far as I could tell). I feel it would be best if this PR was reviewed and merged and have the remaining animation problem be tracked by a separate issue and tackled another time.

**Comment by NathanLovato** [comment]
Thank you very much for the help!

**Pull request merged**
