### PR TITLE
Fix missing `ext_resource` UIDs by resaving all scenes in Godot 4.0.4

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes some of the warnings in #26, and new ones introduced after re-saving some scenes but not all. I went through all scenes twice, which should hopefully make all of them happy.

Needs testing on different OSes and possibly Godot versions to see whether some of these would keep changing in a non deterministic way. I did these changes with Godot 4.0.4 on Linux.

Draft for now as I'm going to redo it after another PR that removes binary data from scene files, to avoid these humongous diffs.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks! I think we can move the project to 4.1. Here it's working fine in 4.1 with your PR, it does get rid of all warnings here, but I'm on Linux. I'll ask teammates to test on other OSes

**Comment by akien-mga** [comment]
Yeah I need to do some more work on #29 first, there seems to be something really nasty happening in this project on each save. But indeed after fixes it seems to work in 4.1, I just had a case where some meshes and materials got corrupted so I'm taking it step by step.

**Comment by NathanLovato** [comment]
Mike from our team tested and he reported no errors on MacOS

**Comment by akien-mga** [comment]
Great!

For the record, the diff in this PR is 17MB, even though I haven't touched any of the big arrays. Just because I modified some values which are close to big arrays, so they get repeated in the text diff.

That's why #29 is a pre-requisite to merging this if we don't want to needlessly increase the size of the `.git` folder.

**Comment by akien-mga** [comment]
Superseded by #30.

**Pull request closed without merging**
